<?php
declare(strict_types=1);

/**
 * Database Connection Manager (PDO Singleton)
 * Supports dynamic configuration via web setup wizard (db_config.php), environment variables, or defaults.
 */
class Database {
    private static ?PDO $instance = null;
    private static string $configFile = __DIR__ . '/db_config.php';

    public static function getConfigFile(): string {
        return self::$configFile;
    }

    public static function getConfig(): array {
        $defaults = [
            'host' => getenv('DB_HOST') ?: 'localhost',
            'port' => getenv('DB_PORT') ?: '3306',
            'name' => getenv('DB_NAME') ?: 'nigiwaig_mpm',
            'user' => getenv('DB_USER') ?: 'nigiwaig_mpm',
            'pass' => getenv('DB_PASS') !== false ? getenv('DB_PASS') : 'Zxcv@321',
            'charset' => 'utf8mb4'
        ];

        if (file_exists(self::$configFile)) {
            $saved = include self::$configFile;
            if (is_array($saved)) {
                return array_merge($defaults, $saved);
            }
        }

        return $defaults;
    }

    public static function isConfigured(): bool {
        return file_exists(self::$configFile);
    }

    public static function saveConfig(array $config): bool {
        $data = [
            'host' => trim($config['host'] ?? 'localhost'),
            'port' => trim($config['port'] ?? '3306'),
            'name' => trim($config['name'] ?? 'nigiwaig_mpm'),
            'user' => trim($config['user'] ?? 'nigiwaig_mpm'),
            'pass' => $config['pass'] ?? '',
            'charset' => 'utf8mb4'
        ];

        $content = "<?php\n// Auto-generated by Nigiwai PM Setup Wizard\nreturn " . var_export($data, true) . ";\n";
        return file_put_contents(self::$configFile, $content) !== false;
    }

    public static function testConnection(array $config): array {
        $host = trim((string)($config['host'] ?? 'localhost'));
        $port = trim((string)($config['port'] ?? '3306'));
        $db   = trim((string)($config['name'] ?? ''));
        $user = trim((string)($config['user'] ?? ''));
        $pass = (string)($config['pass'] ?? '');
        $charset = 'utf8mb4';

        if (empty($host) || empty($user)) {
            return ['success' => false, 'error' => 'กรุณากรอก Database Host และ Database Username'];
        }

        try {
            $dsn = "mysql:host={$host};port={$port};charset={$charset}";
            if (!empty($db)) {
                $dsn .= ";dbname={$db}";
            }
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_TIMEOUT => 5,
                PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4"
            ]);
            $pdo->query("SELECT 1");
            return ['success' => true, 'message' => 'เชื่อมต่อฐานข้อมูลสำเร็จ!'];
        } catch (Throwable $e) {
            return ['success' => false, 'error' => $e->getMessage()];
        }
    }

    public static function getConnection(): PDO {
        if (self::$instance === null) {
            $config = self::getConfig();
            $host = $config['host'];
            $port = $config['port'];
            $db   = $config['name'];
            $user = $config['user'];
            $pass = $config['pass'];
            $charset = $config['charset'] ?? 'utf8mb4';

            $dsn = "mysql:host={$host};port={$port};dbname={$db};charset={$charset}";
            $options = [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
                PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4"
            ];

            try {
                self::$instance = new PDO($dsn, $user, $pass, $options);
            } catch (Throwable $e) {
                if (php_sapi_name() !== 'cli' && (!isset($_SERVER['CONTENT_TYPE']) || !str_contains($_SERVER['CONTENT_TYPE'], 'json'))) {
                    if (!self::isConfigured() && !str_contains($_SERVER['REQUEST_URI'] ?? '', 'setup.php')) {
                        header('Location: setup.php');
                        exit;
                    }
                }
                http_response_code(500);
                header('Content-Type: application/json; charset=utf-8');
                echo json_encode([
                    'success' => false,
                    'error' => 'Database connection failed: ' . $e->getMessage(),
                    'setup_url' => 'setup.php'
                ], JSON_UNESCAPED_UNICODE);
                exit;
            }
        }
        return self::$instance;
    }
}
